=== mpound/carma/conf/imr/domain.dtd
<!ENTITY defargs "">
<!ENTITY defoptargs "">
<!ENTITY defdirectory "/home/control">
<!ENTITY defactivatepoas "no">
<!ENTITY defmaxspawncount "2">
<!ENTITY deffailtimeout "60">
<!ENTITY defupdatetimeout "20000">
<!ENTITY defemulate "true">
<!ENTITY defcritical "false">
<!ENTITY BIN_DIR "/opt/rt/bin">
<!ENTITY TRACE_OFF "traceFile=syslog traceLevel=8">
<!ENTITY TRACE_SYSLOG "traceFile=syslog traceLevel=">
<!ENTITY EMULATE "emulate=&defemulate;">

<!ENTITY acc      "acc">
<!ENTITY wbdc     "wbdc">
<!ENTITY wbcor1   "wbcor1">
<!ENTITY wbcor2   "wbcor2">
<!ENTITY wbcor3   "wbcor3">
<!ENTITY wbcor4   "wbcor4">
<!ENTITY wbcor5   "wbcor5">
<!ENTITY wbcor6   "wbcor6">
<!ENTITY wbcor7   "wbcor7">
<!ENTITY wbcor8   "wbcor8">
<!ENTITY ovro1    "ovro1">
<!ENTITY ovro2    "ovro2">
<!ENTITY ovro3    "ovro3">
<!ENTITY ovro4    "ovro4">
<!ENTITY ovro5    "ovro5">
<!ENTITY ovro6    "ovro6">
<!ENTITY bima1    "bima1">
<!ENTITY bima2    "bima2">
<!ENTITY bima3    "bima3">
<!ENTITY bima4    "bima4">
<!ENTITY bima5    "bima5">
<!ENTITY bima6    "bima6">
<!ENTITY bima7    "bima7">
<!ENTITY bima8    "bima8">
<!ENTITY bima9    "bima9">
<!ENTITY database "database">
<!ENTITY corba    "corba">

<!-- Startup priority entities -->
<!ENTITY corba-services "0">
<!ENTITY monitor-core "1">
<!ENTITY monitor "2"> 
<!ENTITY pre-subsystem "3"> 
<!ENTITY subsystem-core "4"> 
<!ENTITY subsystem "6">
<!ENTITY control "7">
<!ENTITY other "9">

<!ELEMENT domain (oad*)>
<!ELEMENT oad (server+)>
<!ATTLIST oad hostname CDATA #REQUIRED>
<!ATTLIST oad system (data|monitor|control|interferometry|correlator|ovro|bima|sza|misc) 
                "misc">
<!ELEMENT server ANY>
<!ATTLIST server name CDATA #REQUIRED>
<!ATTLIST server path CDATA #REQUIRED>
<!ATTLIST server args CDATA "&defargs;">
<!ATTLIST server optargs CDATA "&defoptargs;">
<!ATTLIST server directory CDATA "&defdirectory;">
<!ATTLIST server activatepoas (yes|no) "&defactivatepoas;">
<!ATTLIST server maxspawncount CDATA "&defmaxspawncount;">
<!ATTLIST server failtimeout CDATA "&deffailtimeout;">
<!ATTLIST server updatetimeout CDATA "&defupdatetimeout;">
<!ATTLIST server system (data|monitor|control|interferometry|correlator|ovro|bima|sza|misc|unknown) "unknown">
<!ATTLIST server startup-priority (0|1|2|3|4|5|6|7|8|9) "9">
<!ATTLIST server critical (true|false) "&defcritical;">

=== mpound/carma/conf/imr/erikLocalPipelineTest.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd"[
    <!ENTITY BIN_DIR "./bin/">
    <!ENTITY STATE_DIR "/tmp/eml/state/">
    <!ENTITY RUN_DIR "/home/eml/projects/carma/Carma/devel/build/">
    <!ENTITY DEFAULT_DIR "/home/eml/projects/carma/Carma/devel/build/">
    <!ENTITY MODE "shared">
    <!ENTITY DBMS "useDBMS=false">
    <!ENTITY USE_DB "useDBMS=false">
    <!ENTITY LOG "">
    <!ENTITY STATE "shared">
    <!ENTITY SIMCARMAINI "correlator/carma15-test.ini">
    <!ENTITY SIMCARMABANDXML SYSTEM "simCarmaBand.xml">
    <!ENTITY SIMBANDSERVER "localhost">
    <!ENTITY SIMCOBRASERVER "localhost">
    <!ENTITY SIMWIDEBANDXML SYSTEM "simWideBand.xml" >
    <!ENTITY SIMCOBRAINI "correlator/sza16Sim.ini" >
    <!ENTITY SIMULATE "true">
]>

<domain>

    <oad hostname="s3.carma.pvt">

       <server name="FrameCollator" 
                path="&BIN_DIR;frameCollator"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; delay=600" 
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                system="monitor"
                critical="true"
                startup-priority="&monitor-core;"/>
        
       <server name="FaultSystem" 
                path="&BIN_DIR;faultSystem"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; outputCMS=intermediate"
                system="monitor"
                startup-priority="&monitor;"/>

        <server name="signalPathFSP" 
                path="&BIN_DIR;/frameScriberPublisher"
	        directory="&RUN_DIR;" 
	        args="&LOG; &DBMS;  
                subsystem=signalpath delay=145"
                startup-priority="&monitor;" />
    
        <server name="SignalPathMapper" 
                path="&BIN_DIR;/carmaSignalPathMapper"
	        directory="&RUN_DIR;" 
                args="&LOG;"
                startup-priority="&subsystem;"/>

        <server name="Subarray1" 
                path="&BIN_DIR;/subarrayControl"
                directory="&RUN_DIR;" 
                args="subarrayNo=1 runSAT=true &LOG; &DBMS;"
                optargs="-ORBSvcConf &BIN_DIR;/../conf/tao/fc.conf"
                system="control" critical="true" 
                startup-priority="&control;"/>

        <server name="Subarray2" 
                path="&BIN_DIR;/subarrayControl"
                directory="&RUN_DIR;" 
                args="subarrayNo=2 runSAT=true &LOG; &DBMS; " 
                optargs="-ORBSvcConf &BIN_DIR;/../conf/tao/fc.conf"
                system="control" critical="true"
                startup-priority="&control;"/>

        <server name="ControlState" path="&BIN_DIR;/carmaControlState"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; statedir=&STATE_DIR;"
                system="control" critical="false" />

        <server name="ControlFSP" 
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=control"
                system="monitor"
                startup-priority="&monitor;"/>
        
        <server name="CorrDataRemapper" 
                path="&BIN_DIR;carmaCorrelatorDataRemapper"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS;"
                startup-priority="&subsystem-core;"
                system="data"
                critical="true" />

        <server name="AstroFSP" 
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=astro delay=400" 
                startup-priority="&monitor;"/>

<!-- ************************************************************ -->
<!-- Spectral line pipeline core components -->
<!-- ************************************************************ -->

        <server name="SlcDataCatcher" 
                path="&BIN_DIR;catchData"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; mode=sl"
                system="data" critical="true"
                startup-priority="&subsystem;"/>

        <server name="SlPipelineFSP" 
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=slpipeline delay=400" 
                startup-priority="&monitor;"/>

        <server name="SlPipeline" 
                path="&BIN_DIR;pipeline"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; mode=sl vbdir=/tmp/eml monitorDelay=350 traceLevel=0" 
                system="data" critical="true"
                startup-priority="&subsystem;" />

<!-- ************************************************************ -->
<!-- Spectral sim server for SLC band 1 -->
<!-- ************************************************************ -->

        <server name="SimSlcBand1FSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &USE_DB; subsystem=CarmaSlcBand1"
                system="correlator" />
        
        <server name="SimSlcBand1CarmaServer" path="&BIN_DIR;CorrelatorCarmaServer"
                directory="&RUN_DIR;" 
                args="b=1 p=19001 f=correlator/slcorrelator.conf hwtype=carma &LOG;"
                critical="true" 
                system="correlator" 
                startup-priority="&pre-subsystem;"/>                

        <server name="SimSlcBand1Server" path="&BIN_DIR;/CorrelatorBandServer"
                directory="&RUN_DIR;" 
                args="&LOG; y=true b=1 simulate=&SIMULATE; i=&SIMCARMAINI;" 
                critical="true" 
                system="correlator" 
                startup-priority="&subsystem;"/>

    </oad>

</domain>

=== mpound/carma/conf/imr/spica.xml
<?xml version="1.0"?>

<!-- Include the domain dtd definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
        <!ENTITY BIN_DIR "/export/scr2/friedel/carma/carma_build/install/bin">
        <!ENTITY DEFAULT_DIR "/export/scr2/friedel/carma">
        <!ENTITY CONF_DIR "/export/scr2/friedel/carma/carma_build/install/conf/imr">
        <!ENTITY EMULATE "true">
        <!ENTITY LOG "traceFile=/export/scr2/friedel/carma/logs/trace.log traceLevel=4 logfile=/export/scr2/friedel/carma/logs/sys.log">
        <!ENTITY USE_DB "useDBMS=false">
]>


<!-- 
        Configuration for Doug's laptop computer, but it is generic to any
        single computer (run it with imr=localhost). (Based on marcLocal.xml)  
 -->

<!-- @version -->
<domain>
 
    
    <oad hostname="localhost">
        <server name="FrameCollator" path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;"  
                args="&LOG; &USE_DB; " />
        <server name="controlFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; subsystem=control" />

        <server name="dataflowFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; subsystem=dataflow delay=130"/>
        <server name="projectDatabaseManagerFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; subsystem=projectdatabasemanager"/>

        <server name="Subarray1" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="subarrayNo=1 runSAT=true &LOG; &USE_DB;"/>
        <server name="ProjectDatabaseManagerHost" path="&BIN_DIR;/carmaProjectDatabaseManagerHost"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; hostname=localhost database=test rt=false" />
       </oad>  
       
</domain>
