=== mpound/carma/conf/imr/domain.dtd
<!ENTITY defargs "">
<!ENTITY defoptargs "">
<!ENTITY defdirectory "/home/control">
<!ENTITY defactivatepoas "no">
<!ENTITY defmaxspawncount "2">
<!ENTITY deffailtimeout "60">
<!ENTITY defupdatetimeout "20000">
<!ENTITY defemulate "true">
<!ENTITY defcritical "false">
<!ENTITY BIN_DIR "/opt/rt/bin">
<!ENTITY TRACE_OFF "traceFile=syslog traceLevel=8">
<!ENTITY TRACE_SYSLOG "traceFile=syslog traceLevel=">
<!ENTITY EMULATE "emulate=&defemulate;">

<!ENTITY acc      "acc">
<!ENTITY wbdc     "wbdc">
<!ENTITY wbcor1   "wbcor1">
<!ENTITY wbcor2   "wbcor2">
<!ENTITY wbcor3   "wbcor3">
<!ENTITY wbcor4   "wbcor4">
<!ENTITY wbcor5   "wbcor5">
<!ENTITY wbcor6   "wbcor6">
<!ENTITY wbcor7   "wbcor7">
<!ENTITY wbcor8   "wbcor8">
<!ENTITY ovro1    "ovro1">
<!ENTITY ovro2    "ovro2">
<!ENTITY ovro3    "ovro3">
<!ENTITY ovro4    "ovro4">
<!ENTITY ovro5    "ovro5">
<!ENTITY ovro6    "ovro6">
<!ENTITY bima1    "bima1">
<!ENTITY bima2    "bima2">
<!ENTITY bima3    "bima3">
<!ENTITY bima4    "bima4">
<!ENTITY bima5    "bima5">
<!ENTITY bima6    "bima6">
<!ENTITY bima7    "bima7">
<!ENTITY bima8    "bima8">
<!ENTITY bima9    "bima9">
<!ENTITY database "database">
<!ENTITY corba    "corba">

<!-- Startup priority entities -->
<!ENTITY corba-services "0">
<!ENTITY monitor-core "1">
<!ENTITY monitor "2"> 
<!ENTITY pre-subsystem "3"> 
<!ENTITY subsystem-core "4"> 
<!ENTITY subsystem "6">
<!ENTITY control "7">
<!ENTITY other "9">

<!ELEMENT domain (oad*)>
<!ELEMENT oad (server+)>
<!ATTLIST oad hostname CDATA #REQUIRED>
<!ATTLIST oad system (data|monitor|control|interferometry|correlator|ovro|bima|sza|misc) 
                "misc">
<!ELEMENT server ANY>
<!ATTLIST server name CDATA #REQUIRED>
<!ATTLIST server path CDATA #REQUIRED>
<!ATTLIST server args CDATA "&defargs;">
<!ATTLIST server optargs CDATA "&defoptargs;">
<!ATTLIST server directory CDATA "&defdirectory;">
<!ATTLIST server activatepoas (yes|no) "&defactivatepoas;">
<!ATTLIST server maxspawncount CDATA "&defmaxspawncount;">
<!ATTLIST server failtimeout CDATA "&deffailtimeout;">
<!ATTLIST server updatetimeout CDATA "&defupdatetimeout;">
<!ATTLIST server system (data|monitor|control|interferometry|correlator|ovro|bima|sza|misc|unknown) "unknown">
<!ATTLIST server startup-priority (0|1|2|3|4|5|6|7|8|9) "9">
<!ATTLIST server critical (true|false) "&defcritical;">

=== mpound/carma/conf/imr/erikLocalMpstoreTest.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd"[
    <!ENTITY BIN_DIR "./bin/">
    <!ENTITY RUN_DIR "/home/eml/projects/carma/Carma/devel/build/">
    <!ENTITY DEFAULT_DIR "/home/eml/projects/carma/Carma/devel/build/">
    <!ENTITY DBMS "useDBMS=false">
    <!ENTITY USE_DB "useDBMS=false">
    <!ENTITY LOG "">
]>

<domain>


    <oad hostname="s3.carma.pvt">

       <server name="FrameCollator" 
                path="&BIN_DIR;frameCollator"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; delay=600" 
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                system="monitor"
                critical="true"
                startup-priority="&monitor-core;"/>
        
       <server name="FaultSystem" 
                path="&BIN_DIR;faultSystem"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; outputCMS=intermediate"
                system="monitor"
                startup-priority="&monitor;"/>

        <server name="signalPathFSP" 
                path="&BIN_DIR;/frameScriberPublisher"
	        directory="&RUN_DIR;" 
	        args="&LOG; &DBMS;  
                subsystem=signalpath delay=145"
                startup-priority="&monitor;" />
    
        <server name="SignalPathMapper" 
                path="&BIN_DIR;/carmaSignalPathMapper"
	        directory="&RUN_DIR;" 
                args="&LOG;"
                startup-priority="&subsystem;"/>

        <server name="Subarray1" 
                path="&BIN_DIR;/subarrayControl"
                directory="&RUN_DIR;" 
                args="subarrayNo=1 runSAT=true &LOG; &DBMS;"
                optargs="-ORBSvcConf &BIN_DIR;/../conf/tao/fc.conf"
                system="control" critical="true" 
                startup-priority="&control;"/>

        <server name="Subarray2" 
                path="&BIN_DIR;/subarrayControl"
                directory="&RUN_DIR;" 
                args="subarrayNo=2 runSAT=true &LOG; &DBMS; " 
                optargs="-ORBSvcConf &BIN_DIR;/../conf/tao/fc.conf"
                system="control" critical="true"
                startup-priority="&control;"/>

        <server name="ControlState" path="&BIN_DIR;/carmaControlState"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; statedir=&RUN_DIR;"
                system="control" critical="false" />

        <server name="ControlFSP" 
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=control"
                system="monitor"
                startup-priority="&monitor;"/>
        
        <server name="carmaMonitorSystemServer" 
                path="&BIN_DIR;/tCmss"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS;"
                startup-priority="&monitor;"/>

        <server name="carmaFastMonitorSystemReserver" 
                path="&BIN_DIR;/tCmsr"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; host=build.ovro.pvt"
                startup-priority="&monitor;"/>

        <server name="carmaMonitorSystemArchiverOneMinute" 
                path="&BIN_DIR;/tCmsa"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; host=localhost clientPort=5666 arcdir=/tmp/mpstore/oneMinute"
                startup-priority="&monitor;"/>

        <server name="carmaMonitorSystemArchiverHalfSecond" 
                path="&BIN_DIR;/tCmsa"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; host=localhost clientPort=5666 nframe=1 arcdir=/tmp/mpstore/halfSecond"
                startup-priority="&monitor;"/>

        <server name="carmaSlowMonitorSystemReserver" 
                path="&BIN_DIR;/tCmsr"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; host=build.ovro.pvt serverPort=5667"
                startup-priority="&monitor;"/>

        <server name="carmaMonitorSystemArchiverWbcorr" 
                path="&BIN_DIR;/tCmsa"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; host=localhost clientPort=5666 corr=wb arcdir=/tmp/mpstore/wbcorr"
                startup-priority="&monitor;"/>

        <server name="carmaMonitorSystemArchiverSlcorr" 
                path="&BIN_DIR;/tCmsa"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; host=localhost clientPort=5666 corr=sl arcdir=/tmp/mpstore/slcorr"
                startup-priority="&monitor;"/>

    </oad>

</domain>

=== mpound/carma/conf/imr/mpDBWriterLocal.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
	<!ENTITY BIN_DIR "/data/beren/dmehring/carma_build/bin">
	<!ENTITY DEFAULT_DIR "/data/beren/dmehring/carma_build">
]>

<!-- Configuration for standalone testing all of carma on a single machine.
     
     Note: the use of "localhost" is fine is this file for a single machine
     but very hazardous in a multi-machine configuration.
 -->

<!-- @version -->
<domain>
 
    
    <oad hostname="localhost">
        <server name="FrameCollator" path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;"  
                args=""/>
        <server name="FSPwbdc" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=wbdc delay=300"/>
        <server name="FSPtest" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=test"/>

        <server name="WRtest" path="&BIN_DIR;/testMPwriterReader"
                directory="&DEFAULT_DIR;" 
                args="" />
        <server name="HostWbdc" path="&BIN_DIR;/carmaWbdcHost"
                directory="&DEFAULT_DIR;" 
                args="emulate=true"/>
        <server name="wbPipelineFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=wbpipeline" />
<!--
        <server name="WbDataCatcher" path="&BIN_DIR;/catchData"
                directory="&DEFAULT_DIR;"  
                args=" &LOG; mode=wb" />                
        <server name="WbIntegrator" path="&BIN_DIR;/correlatorIntegrator"
                directory="&DEFAULT_DIR;"  
                args="&LOG; " />
-->
    </oad>




</domain>

=== mpound/carma/conf/imr/erikLocalAntennaTest.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd"[
    <!ENTITY BIN_DIR "./bin/">
    <!ENTITY RUN_DIR "/home/eml/projects/carma/Carma/devel/build/">
    <!ENTITY DEFAULT_DIR "/home/eml/projects/carma/Carma/devel/build/">
    <!ENTITY DBMS "useDBMS=false">
    <!ENTITY USE_DB "useDBMS=false">
    <!ENTITY LOG "">
]>

<domain>

    <oad hostname="s3.carma.pvt">

       <server name="FrameCollator" 
                path="&BIN_DIR;frameCollator"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; delay=600" 
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                system="monitor"
                critical="true"
                startup-priority="&monitor-core;"/>
        
       <server name="FaultSystem" 
                path="&BIN_DIR;faultSystem"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; outputCMS=intermediate"
                system="monitor"
                startup-priority="&monitor;"/>

        <server name="Subarray1" 
                path="&BIN_DIR;/subarrayControl"
                directory="&RUN_DIR;" 
                args="subarrayNo=1 runSAT=true &LOG; &DBMS;"
                optargs="-ORBSvcConf &BIN_DIR;/../conf/tao/fc.conf"
                system="control" critical="true" 
                startup-priority="&control;"/>

        <server name="Subarray2" 
                path="&BIN_DIR;/subarrayControl"
                directory="&RUN_DIR;" 
                args="subarrayNo=2 runSAT=true &LOG; &DBMS; " 
                optargs="-ORBSvcConf &BIN_DIR;/../conf/tao/fc.conf"
                system="control" critical="true"
                startup-priority="&control;"/>

        <server name="ControlState" path="&BIN_DIR;/carmaControlState"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; statedir=&RUN_DIR;"
                system="control" critical="false" />

        <server name="ControlFSP" 
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=control"
                system="monitor"
                startup-priority="&monitor;"/>
        
       <server name="Sza1FSP" 
               path="&BIN_DIR;/frameScriberPublisher"
               directory="&RUN_DIR;" 
               args="&LOG; &DBMS; subsystem=sza1 delay=275" 
               startup-priority="&monitor;" />

       <server name="Sza1Control" 
               path="&BIN_DIR;/szaAntennaControl"
               args="&LOG; antenna=0 simcanbus=t simpmac=t host=localhost connect=f" />

    </oad>

</domain>

=== mpound/carma/conf/imr/iraLocal.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd"[
    <!ENTITY BIN_DIR "./bin/">
    <!ENTITY RUN_DIR "/home/iws/devel/carma-git/build">
    <!ENTITY DBMS "useDBMS=false">
    <!ENTITY LOG "">
]>

<!-- $Id: iraLocal.xml,v 1.11 2013/04/09 23:06:23 abeard Exp $ -->
<domain>

    <oad hostname="reimu.ovro.pvt">

        <!-- Core Monitor -->
        <server name="FrameCollator"
                path="&BIN_DIR;frameCollator"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; delay=600"
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                system="monitor"
                critical="true"
                startup-priority="&monitor-core;"/>

        <server name="FaultSystem"
                path="&BIN_DIR;faultSystem"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; alarmFile=fault/test/alarm_good.xml blankFlagFile=fault/test/bf_good.xml runEmailService=false"
                startup-priority="&monitor-core;"/>

        <server name="ControlFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=control"
                critical="false" />

        <server name="Subarray1"
                path="&BIN_DIR;subarrayControl"
                directory="&RUN_DIR;"
                args="runSAT=true &LOG; &DBMS;"
                critical="true"
                startup-priority="&control;" />

        <server name="ControlState"
                path="&BIN_DIR;/carmaControlState"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; statedir=/tmp/state "
                critical="false"/>

        <server name="DelayEngineFSP"
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=delayEngine delay=250"
                critical="false" />


        <!-- Process Monitor -->
        <server name="ProcessMonitorFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=Imr delay=150" />

        <server name="ProcessMonitor" path="&BIN_DIR;/processMonitor"
                directory="&RUN_DIR;" 
                args="&LOG; useDBMS=true file=&RUN_DIR;/conf/imr/alarmLocal.xml  writedelay=0.110 poll=5"
                system="monitor" critical="true" />

        <server name="alarmFSP"
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=alarm"/>

        <server name="alarmControl"
                path="&BIN_DIR;/carmaAlarm"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; mode=control"/>

        <!-- Pipeline -->
        <server name="SlcDataCatcher"
                path="&BIN_DIR;catchData"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS;  mode=sl"
                system="misc"
                startup-priority="&subsystem;"/>

        <server name="SlPipelineFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=slpipeline delay=400"
                startup-priority="&monitor;"/>

        <server name="SlPipeline"
                path="&BIN_DIR;pipeline"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; mode=sl vbdir=/tmp"
                system="correlator"
                startup-priority="&subsystem;" />


        <server name="WbcDataCatcher"
                path="&BIN_DIR;catchData"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; mode=wb"
                startup-priority="&subsystem-core;"/>

        <server name="WbPipelineFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=wbpipeline delay=400"
                startup-priority="&monitor;"/>

        <server name="WbPipeline"
                path="&BIN_DIR;pipeline"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; mode=wb vbdir=/tmp"
                startup-priority="&subsystem;"/>
        <server name="SlcBand1FSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=slcBand1" />

        <!-- Simulated Correlator -->
        <server name="SlcBand1" path="&BIN_DIR;/CorrelatorCarmaServer"
                directory="&RUN_DIR;" 
                args="b=1 p=19001 f=correlator/slcorrelator.conf sim=correlator/labCarma15.ini hwtype=cobra "
                critical="true"/>

        <server name="WbcBand3FSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=wbcBand3"
                 />

        <server name="WbcBand3" path="&BIN_DIR;/CorrelatorCarmaServer"
                directory="&RUN_DIR;" 
                args="b=3 p=19003 f=correlator/wbcorrelator.conf sim=correlator/sza14Sim.ini hwtype=cobra  sl=false"
                critical="true"/>


        <!-- Downconverter -->
        <server name="Sldc"
                path="&BIN_DIR;carmaSldcHost"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; emulate=true sim=true" />

        <server name="SldcFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=Sldc delay=300 " />


        <server name="Wbdc"
                path="&BIN_DIR;carmaWbdcHost"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; emulate=true" />

        <server name="WbdcFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=Wbdc delay=300 " />

    </oad>
</domain>

=== mpound/carma/conf/imr/controlTestLocal.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
	<!ENTITY BIN_DIR "/home/mpound/src/carma/bin">
	<!ENTITY DEFAULT_DIR "/home/mpound/src/carma">
        <!ENTITY LOG "logfile=/var/carma/log/carma.log">
]>

<!-- Configuration for standalone testing all of carma on a single machine.
     
     Note: the use of "localhost" is fine is this file for a single machine
     but very hazardous in a multi-machine configuration.
 -->

<!-- @version -->
<domain>
 
    
    <oad hostname="localhost">
              
 
        <server name="FSPtest" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=test" />
        <server name="FSPwbdc" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=wbdc delay=300"/>
        <server name="FSPloberotator" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=loberotator" />
        <server name="FSPdelayEngine" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=delayEngine" />
        <server name="ovro1FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro1"/>
        <server name="ovro2FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro2"/>
        <server name="ovro3FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro3"/>
        <server name="ovro4FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro4"/>
        <server name="ovro5FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro5"/>
        <server name="ovro6FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro6"/>
    
        <server name="HostWbdc" path="&BIN_DIR;/carmaWbdcHost"
                directory="&DEFAULT_DIR;" 
                args="emulate=true logfile=/var/log/carma"/>
        <server name="HostLobeRotator" path="&BIN_DIR;/carmaLoberotatorHost"
                directory="&DEFAULT_DIR;" 
                args="emulate=true" />
<!--
        <server name="HostDelayEngine" path="&BIN_DIR;/DelayEngine"
                directory="&DEFAULT_DIR;"   
                args="emulate=true"/>
-->
        <server name="TestFeed" path="&BIN_DIR;/testMPwriterReader"
                directory="&DEFAULT_DIR;"   
                args="writeOnly=true "/>

        <server name="DriveControlOvro1" path="&BIN_DIR;/ovroDriveControl"
                directory="&DEFAULT_DIR;"  
                args="ant=1 c=carma.ovro1.DriveControl"/>
        <server name="DriveControlOvro2" path="&BIN_DIR;/ovroDriveControl"
                directory="&DEFAULT_DIR;"  
                args="ant=3 c=carma.ovro2.DriveControl"/>
        <server name="DriveControlOvro3" path="&BIN_DIR;/ovroDriveControl"
                directory="&DEFAULT_DIR;"  
                args="ant=3 c=carma.ovro3.DriveControl"/>
        <server name="DriveControlOvro4" path="&BIN_DIR;/ovroDriveControl"
                directory="&DEFAULT_DIR;"  
                args="ant=4 c=carma.ovro4.DriveControl"/>
        <server name="DriveControlOvro5" path="&BIN_DIR;/ovroDriveControl"
                directory="&DEFAULT_DIR;"  
                args="ant=5 c=carma.ovro5.DriveControl"/>
        <server name="DriveControlOvro6" path="&BIN_DIR;/ovroDriveControl"
                directory="&DEFAULT_DIR;"  
                args="ant=6 c=carma.ovro6.DriveControl"/>
        <server name="RemoteCanServer" path="&BIN_DIR;/canOverIpServer"
                directory="&DEFAULT_DIR;"   
                args=""/>
 
        <server name="FrameCollator" path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;"  
                args=""/>
 
    </oad>

     <!-- OVRO antenna receiver lab PXE Client -->
    <!-- <oad hostname="ovrolab" -->
        <!-- Add servers here -->
    <!-- </oad> -->
    
    
</domain>

=== mpound/carma/conf/imr/alarmLocal.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd"[
    <!ENTITY BIN_DIR "./bin/">
    <!ENTITY RUN_DIR "/home/iws/devel/carma-git/build">
    <!ENTITY DBMS "useDBMS=false">
    <!ENTITY LOG "">
]>

<!-- $Id: alarmLocal.xml,v 1.21 2014/11/03 19:21:22 iws Exp $ -->
<domain>

    <oad hostname="build2.ovro.pvt">

        <!-- Core Monitor -->
        <server name="FrameCollator"
                path="&BIN_DIR;frameCollator"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; delay=600"
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                system="monitor"
                critical="true"
                startup-priority="&monitor-core;"/>

        <server name="FaultSystem"
                path="&BIN_DIR;faultSystem"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; alarmFile=fault/test/alarm_good.xml blankFlagFile=fault/test/bf_good.xml runEmailService=false"
                startup-priority="&monitor-core;"/>

        <server name="ControlFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=control"
                critical="false"
                startup-priority="&monitor;" />

        <server name="Subarray1"
                path="&BIN_DIR;subarrayControl"
                directory="&RUN_DIR;"
                args="runSAT=true &LOG; &DBMS;"
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                critical="true"
                startup-priority="&control;" />

        <server name="ControlState"
                path="&BIN_DIR;/carmaControlState"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; statedir=/tmp"
                critical="false"
                startup-priority="&control;" />

        <server name="DelayEngineFSP"
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=delayEngine delay=250"
                critical="false"
                startup-priority="&monitor;" />

        <!-- Process Monitor -->
        <server name="ProcessMonitorFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=Imr delay=150"
                startup-priority="&monitor;" />

        <server name="ProcessMonitor" path="&BIN_DIR;/processMonitor"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; file=&RUN_DIR;/conf/imr/alarmLocal.xml writedelay=0.110 poll=5"
                system="monitor" critical="true"
                startup-priority="&monitor;" />

        <server name="alarmFSP"
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=alarm"
                startup-priority="&monitor;" />

        <server name="alarmControl"
                path="&BIN_DIR;/carmaAlarm"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; mode=control"
                startup-priority="&subsystem;"/>

        <!-- signal path mapper -->
        <server name="SignalPath" path="&BIN_DIR;/carmaSignalPathMapper"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS;"
                startup-priority="&subsystem;"/>

        <server name="SignalPathFSP"
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS; subsystem=signalPath"
                startup-priority="&monitor;" />

        <!-- weather station -->
        <server name="weatherFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&RUN_DIR;" 
                args="&LOG; &DBMS;  subsystem=weather delay=250"
                startup-priority="&monitor;"/>

        <server name="WeatherHost" path="&BIN_DIR;/weatherStation"
                directory="&RUN_DIR;" 
                args="&DBMS; emulate=true traceFile=syslog traceLevel=0 dps=true ws=true WSdev=/dev/keyspan/port1 DPSdev=/dev/keyspan/port2"
                startup-priority="&subsystem;"/>

        <!-- spectral pipeline (to trigger the PipelineSync application) -->
        <server name="SlPipelineFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG;  &DBMS; subsystem=slpipeline delay=400"
                system="data"
                startup-priority="&monitor;"/>

        <server name="SlDataCatcher" path="&BIN_DIR;/catchData"
                directory="&RUN_DIR;"
                args="&LOG;  &DBMS;  mode=sl"
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                system="data" critical="true"
                startup-priority="&subsystem;"/>

        <server name="SlPipeline" path="&BIN_DIR;/pipeline"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; mode=sl vbdir=/tmp monitorDelay=375"
                system="data" critical="true"
                startup-priority="&subsystem;"/>

        <!-- RTD plotter server and requirements -->
        <server name="PipelineSync" path="&BIN_DIR;/monitorPipelineSync"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS;"
                system="monitor" critical="true"
                startup-priority="&pre-subsystem;"/>
        <server name="carmaMonitorSystemServer"
                path="&BIN_DIR;/tCmss"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS;"
                startup-priority="&monitor;"/>
        <server name="carmaMonitorSystemRtdServer"
                path="&BIN_DIR;/tRtdServerTask"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; host=build2.ovro.pvt clientPort=5665"
                startup-priority="&monitor;"/>

        <!-- CARMA Project Database -->
        <server name="PDB"
                path="&BIN_DIR;/carmaProjectDatabaseManagerHost"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; hostname=rena.ovro.pvt database=test rt=false"
                optargs="-ORBSvcConf &RUN_DIR;/conf/tao/fc.conf"
                critical="true" />

        <server name="PDBFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&RUN_DIR;"
                args="&LOG; &DBMS; subsystem=projectdatabasemanager"
                critical="false"
                startup-priority="&monitor;" />
    </oad>

</domain>
