=== mpound/carma/conf/imr/domain.dtd
<!ENTITY defargs "">
<!ENTITY defoptargs "">
<!ENTITY defdirectory "/home/control">
<!ENTITY defactivatepoas "no">
<!ENTITY defmaxspawncount "2">
<!ENTITY deffailtimeout "60">
<!ENTITY defupdatetimeout "20000">
<!ENTITY defemulate "true">
<!ENTITY defcritical "false">
<!ENTITY BIN_DIR "/opt/rt/bin">
<!ENTITY TRACE_OFF "traceFile=syslog traceLevel=8">
<!ENTITY TRACE_SYSLOG "traceFile=syslog traceLevel=">
<!ENTITY EMULATE "emulate=&defemulate;">

<!ENTITY acc      "acc">
<!ENTITY wbdc     "wbdc">
<!ENTITY wbcor1   "wbcor1">
<!ENTITY wbcor2   "wbcor2">
<!ENTITY wbcor3   "wbcor3">
<!ENTITY wbcor4   "wbcor4">
<!ENTITY wbcor5   "wbcor5">
<!ENTITY wbcor6   "wbcor6">
<!ENTITY wbcor7   "wbcor7">
<!ENTITY wbcor8   "wbcor8">
<!ENTITY ovro1    "ovro1">
<!ENTITY ovro2    "ovro2">
<!ENTITY ovro3    "ovro3">
<!ENTITY ovro4    "ovro4">
<!ENTITY ovro5    "ovro5">
<!ENTITY ovro6    "ovro6">
<!ENTITY bima1    "bima1">
<!ENTITY bima2    "bima2">
<!ENTITY bima3    "bima3">
<!ENTITY bima4    "bima4">
<!ENTITY bima5    "bima5">
<!ENTITY bima6    "bima6">
<!ENTITY bima7    "bima7">
<!ENTITY bima8    "bima8">
<!ENTITY bima9    "bima9">
<!ENTITY database "database">
<!ENTITY corba    "corba">

<!-- Startup priority entities -->
<!ENTITY corba-services "0">
<!ENTITY monitor-core "1">
<!ENTITY monitor "2"> 
<!ENTITY pre-subsystem "3"> 
<!ENTITY subsystem-core "4"> 
<!ENTITY subsystem "6">
<!ENTITY control "7">
<!ENTITY other "9">

<!ELEMENT domain (oad*)>
<!ELEMENT oad (server+)>
<!ATTLIST oad hostname CDATA #REQUIRED>
<!ATTLIST oad system (data|monitor|control|interferometry|correlator|ovro|bima|sza|misc) 
                "misc">
<!ELEMENT server ANY>
<!ATTLIST server name CDATA #REQUIRED>
<!ATTLIST server path CDATA #REQUIRED>
<!ATTLIST server args CDATA "&defargs;">
<!ATTLIST server optargs CDATA "&defoptargs;">
<!ATTLIST server directory CDATA "&defdirectory;">
<!ATTLIST server activatepoas (yes|no) "&defactivatepoas;">
<!ATTLIST server maxspawncount CDATA "&defmaxspawncount;">
<!ATTLIST server failtimeout CDATA "&deffailtimeout;">
<!ATTLIST server updatetimeout CDATA "&defupdatetimeout;">
<!ATTLIST server system (data|monitor|control|interferometry|correlator|ovro|bima|sza|misc|unknown) "unknown">
<!ATTLIST server startup-priority (0|1|2|3|4|5|6|7|8|9) "9">
<!ATTLIST server critical (true|false) "&defcritical;">

=== mpound/carma/conf/imr/bimaLocal.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
	<!ENTITY BIN_DIR "/carma/build/bin">
	<!ENTITY DEFAULT_DIR "/carma/build">
	<!ENTITY DBMS "useDBMS=false">
        <!ENTITY TRACE "traceFile=syslog traceLevel=0">
]>

<!-- @version -->
<domain>
 
    

    <oad hostname="ain.carma.pvt">
        <server name="FrameCollator" path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;"  
                args="&TRACE; &DBMS;" />

        <server name="controlFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;"
                args="&TRACE; &DBMS; subsystem=control"/>

        <server name="alarmFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; subsystem=alarm"/>

        <server name="Subarray1" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="subarrayNo=1 runSAT=true &TRACE; &DBMS;"
                system="control" />

	<server name="delayEngineFSP" path="&BIN_DIR;/frameScriberPublisher"
	        directory="&DEFAULT_DIR;" 
		args="&TRACE; &DBMS; subsystem=delayEngine"/>

	<server name="phaseMonitorFSP" path="&BIN_DIR;/frameScriberPublisher"
	        directory="&DEFAULT_DIR;" 
		args="&TRACE; &DBMS; subsystem=phaseMonitor"/>

    </oad>

    <oad hostname="a1.carma.pvt">
              
        <server name="OTa1" path="&BIN_DIR;/carmaOpticalTel"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1 emulate=true forcetype=bima" />

        <server name="FSPa1" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; subsystem=bima1" />
    
        <server name="THa1" path="&BIN_DIR;/bimaTelemetryHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />

        <server name="DMa1" path="&BIN_DIR;/bimaDriveMgr"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />

        <server name="RMa1" path="&BIN_DIR;/bimaRxMgr"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />

        <server name="MHa1" path="&BIN_DIR;/bimaMonitorHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />

        <server name="IFa1" path="&BIN_DIR;/bimaIFHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />

        <server name="DRa1" path="&BIN_DIR;/bimaDewarReg"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1 reg=true" />

        <server name="FSPloref" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; subsystem=loref" />
    
        <!-- This applies to the 8662 in the 444 lab rack -->
        <server name="LOref" path="&BIN_DIR;/carmaLORefHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; emulate=false synth1_8662=true synth1_gpib=19" />

        <server name="CHa1" path="&BIN_DIR;/bimaControlHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />
    </oad>

</domain>

=== mpound/carma/conf/imr/wbdcSza.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd">

<!-- Configuration for the SZA acc, imr and the wbdc machine.
     It runs the host and monitoring processes.
 -->


<!-- @version -->
<domain>

    <!-- The sza system 'acc' -->
    <oad hostname="szanet.ovro.caltech.edu">
        <server name="FrameCollator" 
            path="/home/scott/carma/install/opti/bin/frameCollator"
            args=""
            directory="/home/scott"  />
       <!--
        <server name="CatchData" 
            path="/home/scott/carma/install/opti/bin/frameCollator"
            args=""
            directory="/home/scott"  />
        -->
     </oad>
    
    <!-- Wideband downconverter -->
    <oad hostname="dcon0">
    
        <server name="HostWbdc" 
            path="/home/scott/carma/install/opti/bin/carmaWbdcHost"
            args="board=0"
            directory="/home/scott"  />
        <server name="HostDelayEngine" 
            path="/home/scott/carma/install/opti/bin/DelayEngine"
            args="" 
            directory="/home/szadaq" />

<!-- *********************************************
        <server name="HostLoberotator" 
            path="/home/scott/carma/install/opti/bin/carmaLoberotatorHost"
            args="board=1" 
            directory="/home/szadaq" />
-->
        <!-- We need three instances of frameScriberPublisher running on this
             machine.  One for each subsystem.  Note that each instance must
             be registered with the IMR under a different name.          -->
        <server name="FSPwbdc" 
             path="/home/scott/carma/install/opti/bin/frameScriberPublisher"
             args="subsystem=wbdc delay=300"
             directory="/home/szadaq" />
        <server name="FSPoberotator" 
             path="/home/scott/carma/install/opti/bin/frameScriberPublisher"
             args="subsystem=loberotator"
             directory="/home/szadaq" />
        <server name="FSPdelayEngine"
            path="/home/scott/carma/install/opti/bin/frameScriberPublisher"
            args="subsystem=delayengine"
            directory="/home/szadaq" />
            
            
        <server name="RemoteCanServer" 
            path="/home/scott/carma/install/opti/bin/canOverIpServer"
            directory="/home/szadaq" 
            args=""  />
    </oad>

    
</domain>

=== mpound/carma/conf/imr/berkeleyLab.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
	<!ENTITY BIN_DIR "/carma/rt/bin">
	<!ENTITY DEFAULT_DIR "/carma/rt">
	<!ENTITY DBMS "useDBMS=false">
        <!ENTITY TRACE "traceFile=syslog traceLevel=0">
        <!ENTITY EMULATE "true">
]>

<!-- @version -->
<domain>
 
    <oad hostname="ain.carma.pvt">
        <server name="FrameCollator" path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;"  
                args="&TRACE; &DBMS;" />

        <server name="FaultSystem" path="&BIN_DIR;/faultSystem"
                directory="&DEFAULT_DIR;"  
                args="&TRACE; &DBMS;" />

<!--
        <server name="delayEngineFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; subsystem=delayEngine"
                system="interferometry" />

        <server name="controlFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; subsystem=control"/>

        <server name="alarmFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;"
                args="&TRACE; &DBMS; subsystem=alarm"/>

        <server name="Subarray1" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="subarrayNo=1 runSAT=true &TRACE; &DBMS;"
                system="control" />

        <server name="Subarray2" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="runSAT=true subarrayNo=2 &TRACE; &DBMS;" />

        <server name="Subarray3" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="runSAT=true subarrayNo=3 &TRACE; &DBMS;"
                system="control" />

        <server name="Subarray4" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="runSAT=true subarrayNo=4 &TRACE; &DBMS;"
                system="control" />

	<server name="delayEngineFSP" path="&BIN_DIR;/frameScriberPublisher"
	        directory="&DEFAULT_DIR;" 
		args="&TRACE; &DBMS; subsystem=delayEngine"/>

	<server name="alarmWatch" path="&BIN_DIR;/carmaAlarm"
	        directory="&DEFAULT_DIR;" 
		args="&TRACE; &DBMS; imrpoa=true mode=watch emulate=true"/>
-->

        <!-- Process monitor -->
<!--
        <server name="ProcessMonitorFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;"  
                args="&TRACE; &DBMS; subsystem=Imr delay=150"
                system="monitor" />

        <server name="ProcessMonitor" path="&BIN_DIR;/processMonitor"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; file=conf/imr/berkeleyLab.xml imrpoa=true writedelay=0.100"
                system="monitor" />
-->

    </oad>

    <oad hostname="a1.carma.pvt">
              
         <server name="RemoteCanA1" path="&BIN_DIR;/canOverIpServer"
                directory="&DEFAULT_DIR;"   
                args="&TRACE; &DBMS; imrpoa=true"
                system="bima" />

        <!--server name="OTa1" path="&BIN_DIR;/carmaOpticalTel"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1 emulate=true forcetype=bima" /-->

        <server name="FSPa1" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; subsystem=bima1" />
    
        <server name="THa1" path="&BIN_DIR;/bimaTelemetryHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; imrpoa=true antenna=a1" />

        <!--server name="DMa1" path="&BIN_DIR;/bimaDriveMgr"
                directory="&DEFAULT_DIR;" 
                args="imrpoa=true &TRACE; &DBMS; antenna=a1" /-->

        <server name="RMa1" path="&BIN_DIR;/bimaRxMgr"
                directory="&DEFAULT_DIR;" 
                args="imrpoa=true &TRACE; &DBMS; antenna=a1" />

        <server name="MHa1" path="&BIN_DIR;/bimaMonitorHost"
                directory="&DEFAULT_DIR;" 
                args="imrpoa=true &TRACE; &DBMS; antenna=a1" />

        <server name="IFa1" path="&BIN_DIR;/bimaIFHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />

        <server name="DRa1" path="&BIN_DIR;/bimaDewarReg"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1 reg=true" />

        <server name="CHa1" path="&BIN_DIR;/bimaControlHost"
                directory="&DEFAULT_DIR;" 
                args="&TRACE; &DBMS; antenna=a1" />
    </oad>
</domain>

=== mpound/carma/conf/imr/sldc.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd"[
    <!ENTITY BIN_DIR "/home/abeard/development/carma/build/bin/">
    <!ENTITY RUN_DIR "/home/abeard/development/carma/build/">
    <!ENTITY LOG "">
]>

<!-- Spectral Line Downconverter local test config.  -->

<domain>

   <oad hostname="localhost">
       
       <server name="FrameCollator"
            path="&BIN_DIR;/frameCollator"
            directory="&RUN_DIR;" 
            args=" &LOG; mode=final"  />
       
       <server name="Subarray1" 
            path="&BIN_DIR;/subarrayControl"
            directory="&RUN_DIR;"  
            args="runSAT=true &LOG;" />

   </oad>
   <oad hostname="canlab.ovro.pvt">
        <server name="SldcFSP" 
            path="&BIN_DIR;frameScriberPublisher"
            args="subsystem=Sldc delay=300 "
            directory="&RUN_DIR;"  />
    
        <server name="Sldc" 
            path="&BIN_DIR;carmaSldcHost"
            args="sim=true emulate=true"
            directory="&RUN_DIR;"  />

         <server name="RemoteCan" path="&BIN_DIR;/canOverIpServer"
                directory="&RUN_DIR;"   
                args=""/>
    
    </oad>

</domain>

=== mpound/carma/conf/imr/sza.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
        <!ENTITY BIN_DIR "/home/scott/carma/install/optimized/bin">
        <!ENTITY DEFAULT_DIR "/home/scott">
        <!ENTITY EMULATE "true">
        <!ENTITY ANT "ovro4">
]>

<!-- SZA system configuration description - Place CARMA applications which
     will be under the control of the IMR here. See 
     carma/conf/exampleCarmaConfig.xml for a detailed tag description. -->

<!-- @version: -->
<domain>
    <!-- Configure the sza acc -->
    <oad hostname="szanet.localnet">
        <!-- FrameCollator must run on acc (szanet) to reap monitor points
             from the various subsystems.                              -->
        <server name="FrameCollator" path="&BIN_DIR;/frameCollator"
            args="" directory="&DEFAULT_DIR;"  />
    </oad>
    <!-- Configure the sza downconverter host machine.  This machine hosts
         the carmaWbdcHost, LobeRotator and DelayEngine applications. -->
    <oad hostname="dcon0.localnet">
        <server name="HostWbdc" path="&BIN_DIR;/carmaWbdcHost"
            args="board=0" directory="&DEFAULT_DIR;" />

<!--   ***Temporarily removed***
        <server name="HostLobeRotator" path="&BIN_DIR;/carmaLoberotatorHost"
            args="board=1" directory="&DEFAULT_DIR;" />
 -->           
 
        <server name="HostDelayEngine" path="&BIN_DIR;/DelayEngine"
            args="" 
            directory="&DEFAULT_DIR;" />
        <!-- We need three instances of frameScriberPublisher running on this
             machine.  One for each subsystem.  Note that each instance must
             be registered with the IMR under a different name.          -->
        <server name="FSPwbdc" 
            path="&BIN_DIR;/frameScriberPublisher"
            args="subsystem=wbdc delay=300"
            directory="&DEFAULT_DIR;">
        </server>
        <server name="FSPloberotator" 
            path="&BIN_DIR;/frameScriberPublisher"
            args="subsystem=loberotator"
            directory="&DEFAULT_DIR;" />
        <server name="FSPdelayEngine"
            path="&BIN_DIR;/frameScriberPublisher"
            args="subsystem=delayengine"
            directory="&DEFAULT_DIR;" />
        <server name="RemoteCanServerWbdc" path="&BIN_DIR;/canOverIpServer"
            directory="&DEFAULT_DIR;"  
            args=""  />
     </oad>
</domain>

=== mpound/carma/conf/imr/tioga.xml
<?xml version="1.0"?>
<!-- $Id: tioga.xml,v 1.61 2014/06/30 18:54:47 scott Exp $ -->

<!-- Include the domain dtd definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
        <!ENTITY TOP_DIR "/home/scott/CARMA/install">
        <!ENTITY BIN_DIR "&TOP_DIR;/bin">
        <!ENTITY DEFAULT_DIR "&TOP_DIR;">
        <!ENTITY EMULATE "true">
        <!ENTITY LOG "traceFile=syslog traceLevel=0">
        <!ENTITY USE_DB "useDBMS=false">
]>

<!-- 
        Configuration for Steve's desktop computer, but it is generic to any
        single computer (run it with imr=localhost).  
 -->

<!-- @version -->
<domain>
 
    
    <oad hostname="localhost">
        <server name="controlFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; subsystem=control"
                startup-priority="&monitor;"/>
        <server name="FrameCollator" path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;"  
                args="&LOG; &USE_DB; mode=raw, clearDelay=30" 
                startup-priority="&monitor-core;"/>
        <server name="loberotatorFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=loberotator &LOG; &USE_DB;"  />
        <server name="delayEngineFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=delayEngine &LOG; &USE_DB;" />
        <server name="ovro1FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro1 &LOG; &USE_DB;" />
        <server name="ovro2FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro2 &LOG; &USE_DB;" />
        <server name="ovro4FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=ovro4 &LOG; &USE_DB;" />

        <server name="Subarray1" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="runSAT=true &LOG; &USE_DB; subarrayNo=1 " 
                optargs="-ORBSvcConf &TOP_DIR;/conf/tao/fc.conf"
                system="control"
                startup-priority="&control;" />
        <server name="Subarray2" path="&BIN_DIR;/subarrayControl"
                directory="&DEFAULT_DIR;"  
                args="runSAT=true &LOG; &USE_DB; subarrayNo=2" 
                optargs="-ORBSvcConf &TOP_DIR;/conf/tao/fc.conf"  
                system="control"
                startup-priority="&control;" />
        <server name="FaultSystem" path="&BIN_DIR;/faultSystem"
                directory="&DEFAULT_DIR;"  
                args="&LOG; &USE_DB; runEmailService=false alarmFile=fault/test/alarm_good.xml blankFlagFile=fault/test/bf_good.xml outputCMS=intermediate"
                startup-priority="&monitor-core;" />
        <server name="ControlState" path="&BIN_DIR;/carmaControlState"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; statedir=/tmp nice=10"
                critical="false" />

        <server name="ProcessMonitorFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;"  
                args="&LOG; &USE_DB; subsystem=Imr delay=150"
                system="monitor" critical="true" 
                startup-priority="&monitor;"/>

        <server name="ProcessMonitor" path="&BIN_DIR;/processMonitor"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; file=/home/scott/CARMA/install/conf/imr/tioga.xml  writedelay=0.100 poll=5"
                system="monitor" critical="true" 
                startup-priority="&subsystem-core;" />

        <server name="signalPathFSP" path="&BIN_DIR;/frameScriberPublisher"
	            directory="&DEFAULT_DIR;" 
	            args="&LOG; &USE_DB;  subsystem=signalpath delay=145"
                startup-priority="&monitor;" />
    
        <server name="SignalPathMapper" path="&BIN_DIR;/carmaSignalPathMapper"
	            directory="&DEFAULT_DIR;" 
                args="&LOG;"
                startup-priority="&subsystem;"/>

        <server name="LobeRotator" path="&BIN_DIR;/carmaLoberotatorHost"
                directory="&DEFAULT_DIR;" 
                args="emulate=true sim=true &LOG; &USE_DB;" />

        <server name="CanHostOvro1" path="&BIN_DIR;/ovroCanHost"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; ant=1 emulate=true simulate=true "/>
        <server name="CanHostOvro2" path="&BIN_DIR;/ovroCanHost"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; ant=2 emulate=true simulate=true "/>
        <server name="CanHostOvro4" path="&BIN_DIR;/ovroCanHost"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; ant=4 emulate=true simulate=true "/>                

        <server name="OTovro2" path="&BIN_DIR;/carmaOpticalTel"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; antenna=ovro2 emulate=true"/>
<!-- SZA Antennas 
  The FSP delay is set to 350msec rather than the nominal 275msec to give
  headroom in case there is an error on CANbus0. Currently this causes a 
  transmission on CANbus1, which is unpopulated, resulting in an infinite
  loop of errors using enough cpu time to delay the publishing of the
  monitor data.
-->

        <server name="Sza3FSP" path="&BIN_DIR;/frameScriberPublisher"
            directory="&DEFAULT_DIR;" 
            args="&LOG; &USE_DB; subsystem=sza3 delay=350" 
            startup-priority="&monitor;" />
        <server name="Sza3Control" path="&BIN_DIR;/szaAntennaControl"
            args="&LOG; antenna=2 simcanbus=t simpmac=t logd=/home/scott/szalog logf=c18 host=localhost ignorewraplogic=f" />
        <server name="OTsza3" path="&BIN_DIR;/carmaOpticalTel"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; antenna=sza3 awdelay=0.15 emulate=true"/>
                
    </oad> 
                
    <!--               
        <server name="sldcFSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=sldc &LOG; &USE_DB;" />
        <server name="slcBand1FSP" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB;  subsystem=CarmaSlcBand1" />
                
        <server name="SlcBand1" path="&BIN_DIR;/CorrelatorCarmaServer"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB;  b=1 p=19001 f=correlator/labcorrelator.conf  sim=correlator/labCarma15.ini hwtype=carma" />

        <server name="Sldc" path="&BIN_DIR;/carmaSldcHost"
                directory="&DEFAULT_DIR;" 
                args="emulate=true &LOG; &USE_DB;" />
       
    </oad>  
    -->

    <!--  
    <oad hostname="canlab">
        <server name="CanHostOvro6" path="&BIN_DIR;/ovroCanHost"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &USE_DB; ant=6 board=0 nofg=false"/>
        
    </oad>        
    -->
       
</domain>

=== mpound/carma/conf/imr/ovroLocal.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
        <!ENTITY BIN_DIR "/opt/rt/bin/">
        <!ENTITY DEFAULT_DIR "/home/control">
        <!ENTITY EMULATE "true">
        <!ENTITY ANT "1">
        <!ENTITY TRACE "traceLevel=0 traceFile=syslog">
        <!ENTITY DBMS "useDBMS=false">
        <!ENTITY LOG "">
]>

<!-- Configuration for standalone testing of an ovro antenna on a single
     machine.  This is most useful for the OvroLab machines (ovrolab and 
     canlab3) since it allows them to run all needed applications without
     a foreign IMR (and hence much decreased robustness).
     
     Note: the use of "localhost" is fine is this file for a single machine
     but very hazardous in a multi-machine configuration.
 -->

<!-- @version -->
<domain>
 
    
    <oad hostname="localhost">

        <!-- Control -->
        <server name="DelayEngineFSP" 
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&BIN_DIR;" 
                args="&LOG; &DBMS; subsystem=delayEngine"
                system="interferometry"
                critical="true"/>

        <server name="Subarray1" 
                path="&BIN_DIR;subarrayControl"
                directory="&BIN_DIR;" 
                args="runSAT=true &LOG; &DBMS;"
                system="control"
                critical="true" />

        <server name="ControlFSP" 
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&BIN_DIR;" 
                args="&LOG; &DBMS; subsystem=control"
                critical="false" />
        
        <!-- Monitor -->
        <server name="FrameCollator" 
                path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;" 
                args=" &DBMS; mode=final"/>

        <!-- Process Monitor -->
        <server name="ProcessMonitorFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&BIN_DIR;" 
                args="&LOG; &DBMS; subsystem=Imr delay=150" />

        <server name="ProcessMonitor"
                path="&BIN_DIR;/processMonitor"
                directory="&BIN_DIR;"
                args="&LOG; &DBMS; file=/opt/rt/conf/imr/ovroLocal.xml  writedelay=0.100" />

        <!-- Ovro Antenna -->
        <server name="FSPOvro&ANT;" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="subsystem=Ovro&ANT; &DBMS;" />
 
         <server name="RemoteCan&ANT;" path="&BIN_DIR;/canOverIpServer"
                directory="&DEFAULT_DIR;"   
                args=" &DBMS;"/>

        <server name="Ovro&ANT;CanHost"
                path="&BIN_DIR;/ovroCanHost"
                directory="&DEFAULT_DIR;" 
                args="ant=&ANT; &TRACE; simulate=true terminate=true  &DBMS;"/>
    </oad>


    
    
</domain>

=== mpound/carma/conf/imr/camera.xml
<?xml version="1.0"?>

<!-- Include the domain DTD definition. -->
<!DOCTYPE domain SYSTEM "domain.dtd" [
        <!ENTITY BIN_DIR "./bin/">
        <!ENTITY DEFAULT_DIR "/home/abeard/CARMA/build">
        <!ENTITY EMULATE "true">
        <!ENTITY ANT "1">
        <!ENTITY TRACE "traceLevel=0 traceFile=syslog">
        <!ENTITY DBMS "useDBMS=false">
        <!ENTITY LOG "">
]>

<!-- 
     Basic configuration for standalone testing of optical camera.

     Note: the use of "localhost" is fine is this file for a single machine
     but very hazardous in a multi-machine configuration.
 -->

<!-- @version -->
<domain>
 
    
    <oad hostname="localhost">

        <!-- Control -->
        <server name="DelayEngineFSP" 
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &DBMS; subsystem=delayEngine"
                system="interferometry"
                critical="true"/>

        <server name="Subarray1" 
                path="&BIN_DIR;subarrayControl"
                directory="&DEFAULT_DIR;" 
                args="runSAT=true &LOG; &DBMS;"
                system="control"
                critical="true" />

        <server name="ControlFSP" 
                path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &DBMS; subsystem=control"
                critical="false" />
        
        <!-- Monitor -->
        <server name="FrameCollator" 
                path="&BIN_DIR;/frameCollator"
                directory="&DEFAULT_DIR;" 
                args="&DBMS; mode=final"/>

        <!-- Process Monitor -->
        <server name="ProcessMonitorFSP"
                path="&BIN_DIR;frameScriberPublisher"
                directory="&DEFAULT_DIR;" 
                args="&LOG; &DBMS; subsystem=Imr delay=150" />

        <server name="ProcessMonitor"
                path="&BIN_DIR;/processMonitor"
                directory="&DEFAULT_DIR;"
                args="&LOG; &DBMS; file=/opt/rt/conf/imr/ovroLocal.xml writedelay=0.100" />

        <!-- Ovro Antenna -->
        <server name="FSPOvro&ANT;" path="&BIN_DIR;/frameScriberPublisher"
                directory="&DEFAULT_DIR;"
                args="subsystem=Ovro&ANT; &DBMS;" />
 
        <server name="Ovro&ANT;CanHost"
                path="&BIN_DIR;/ovroCanHost"
                directory="&DEFAULT_DIR;" 
                args="ant=&ANT; &TRACE; emulate=true simulate=true  &DBMS;"/>

        <server name="Ovro&ANT;Camera"
                path="&BIN_DIR;/carmaOpticalTel"
                directory="&DEFAULT_DIR;"
                args="antenna=ovro&ANT; &DBMS;" />
    </oad>

</domain>
