=== mpound/carma/conf/fault/alarm.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
NOTE: this DTD is meant to be used to verify a pre-processed DAG
NOTE: configuration file only. It does not try to encapsulate any of
NOTE: the shorthands used to construct the original DAG file.
-->

<!-- the top level element -->
<!ELEMENT dag (if|mp|transient|varmap_scope)*>
<!ATTLIST dag alarm_after CDATA #IMPLIED>
<!ATTLIST dag alarm_prefix (sys|sci1|sci2|eng1|eng2|offline) #IMPLIED>
<!ATTLIST dag sound CDATA #IMPLIED>
<!ATTLIST dag type (alarmoutput) #REQUIRED>

<!--
     Capability to stop evaluation based on monitor point value

     This allows you to "chop off" part of the DAG tree based on the
     value of a monitor point. Everything is done with regular expressions
     to allow for arbitrarily complex matching schemes.

     We also allow negation to make certain regular expressions easier
     to write.
-->
<!ELEMENT if (if|mp|transient|varmap_scope)+>
<!ATTLIST if canon CDATA #REQUIRED>
<!ATTLIST if val CDATA #REQUIRED>
<!ATTLIST if negate (true|false) #REQUIRED>

<!--
     A way to add a variable expansion based on a monitor point name

     This is useful for allowing runtime changeable monitor point names
     in child nodes without having to enumerate every possibility in
     <if> conditions.

     The information from this variable map is passed into the email
     system. This allows the template engine to have some information
     about the state of the evaluation. For example: antenna number
     connected to a downconverter input.
-->
<!ELEMENT varmap_scope (if|mp|transient|varmap_scope)+>
<!ATTLIST varmap_scope var CDATA #REQUIRED>
<!ATTLIST varmap_scope canon CDATA #REQUIRED>

<!--
     A transient (runtime-changeable) condition

     This allows you to change the DAG at runtime using a control system
     command. You will use it to disable large sections of monitor points
     during certain array configurations.
-->
<!ELEMENT transient (if|mp|transient|varmap_scope)*>
<!ATTLIST transient cond (alarmEnableSubarray) #REQUIRED>
<!ATTLIST transient subarray CDATA #REQUIRED>

<!--
     Monitor Point

     This represents an instance of a carma::monitor::MonitorPoint in C++.
     It is the only thing that has a value and really effects the "good"
     or "bad" state of a DAG evaluation.

     When an <mp> node has children, this effects evaluation. When a "bad"
     node state is encountered, the children are not evaluated, and the first
     bad node in the tree is reported as the error condition.
-->
<!ELEMENT mp (if|mp|transient|varmap_scope)*>
<!ATTLIST mp canon CDATA #REQUIRED>
<!ATTLIST mp alarm_after CDATA #REQUIRED>
<!ATTLIST mp alarm_prefix (sys|sci1|sci2|eng1|eng2|offline) #REQUIRED>
<!ATTLIST mp sound CDATA #REQUIRED>
<!ATTLIST mp silent (true|false) #REQUIRED>

=== mpound/carma/conf/fault/alarm.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE dag SYSTEM "alarm.dtd" [
	<!ENTITY SCI1 "1">
	<!ENTITY SCI2 "2">
	<!ENTITY SLCBANDS "8">
	<!-- 2012-02-13: wbcband16 offline indefinitely due to hardware failure -->
	<!ENTITY WBCBANDS "15">
	<!ENTITY SLCINPUTS "15">
	<!ENTITY WBCINPUTS "8">
]>

<dag type="alarmoutput" alarm_after="10.0" sound="default">

	<mp canon="Imr.numNotRunningCriticalServers" alarm_after="45.0" />

	<!-- Alarm if the hardware state of the system does not match the requested astroband configuration -->
	<mp canon="SignalPath.Mapping.hardwareConfValid" alarm_after="600.0" />

	<!-- Critical overtemperature alarms -->
	<mp canon="SystemStatus.Places.CorrelatorRoom.currentTemperature" alarm_after="60.0" />
	<mp canon="SystemStatus.Places.ComputerRoomCF.RoomTemp.currentTemperature" alarm_after="60.0" />
	<mp canon="SystemStatus.Places.GeneratorBldg1.currentTemperature" alarm_after="60.0" />
	<mp canon="SystemStatus.Places.GeneratorBldg2.currentTemperature" alarm_after="60.0" />

	<!-- Alarms specific to Subarray 1 (AKA Sci1) -->
	<attrs_scope alarm_prefix="sci1">
		<transient cond="alarmEnableSubarray" subarray="&SCI1;">
			<mp canon="Control.Subarray1.alarm" />
			<mp canon="Control.Subarray1.scriptState" />
			<mp canon="Control.Subarray1.controllerInitialized" />
			<mp canon="SlPipeline.IntegratorStageContainer.IntegratorStage.timeSinceLastIntegration" alarm_after="780.0" />
			<mp canon="SlPipeline.IntegratorStageContainer.IntegratorStage.noData" alarm_after="30.0" />
			<mp canon="SlPipeline.VisBrickStageContainer.VisBrickStage.fileError" alarm_after="30.0" />

			<!-- 1mm weather alarm -->
			<mp canon="Control.Subarray1.alarm1mm" />

			<!-- CARMA Spectral Line Correlator -->
			<range var="bandNoVar" first="1" last="&SLCBANDS;">

				<!-- valid configuration for all bands -->
				<mp canon="Control.SpectralLineCorrelator.SlcBand(bandNoVar).ControlBandPoints.configuration" alarm_after="240.0" />

				<mp canon="SlPipeline.CatchDataBandContainer(bandNoVar).CatchDataBand.duplicateRecordsCaught"/>

				<!-- check that the band is online first -->
				<mp canon="CarmaSlcBand(bandNoVar).online" alarm_after="30.0">

					<!-- failure of a command to the boards -->
					<mp canon="CarmaSlcBand(bandNoVar).commandStatus" alarm_after="30.0" />

					<!-- for each digitizer -->
					<range var="digNoVar" first="1" last="8">
						<mp canon="CarmaSlcBand(bandNoVar).Digitizer(digNoVar).received" alarm_after="30.0">
							<mp canon="CarmaSlcBand(bandNoVar).Digitizer(digNoVar).Power.PowerFailureReason" alarm_after="30.0" />
							<mp canon="CarmaSlcBand(bandNoVar).Digitizer(digNoVar).Temperature.TemperatureStatus" alarm_after="30.0" />
						</mp>
					</range>

					<!-- for each correlator -->
					<range var="corrNoVar" first="1" last="7">
						<mp canon="CarmaSlcBand(bandNoVar).Correlator(corrNoVar).received" alarm_after="30.0">
							<mp canon="CarmaSlcBand(bandNoVar).Correlator(corrNoVar).Power.PowerFailureReason"  alarm_after="30.0"/>
							<mp canon="CarmaSlcBand(bandNoVar).Correlator(corrNoVar).Temperature.TemperatureStatus" alarm_after="30.0" />
						</mp>
					</range>
				</mp>
			</range>

			<!-- CARMA Spectral Line Downconverter -->

			<!-- check that the dcon machine is producing data -->
			<mp canon="Sldc.online">

				<!--
					 Check each dcon band + input

					 - the band + input must be connected to any antenna
					 - the correlator band must be in the same subarray as the antenna
				-->
				<range var="bandNoVar" first="1" last="&SLCBANDS;">
					<range var="inputNoVar" first="1" last="&SLCINPUTS;">
						<varmap_scope var="antNo" canon="SignalPath.Mapping.SlcBand(bandNoVar).Input(inputNoVar).antennaNo">
						<varmap_scope var="corrSubarrayNo" canon="SignalPath.Mapping.SlcBand(bandNoVar).subarrayNo">
							<if canon="Control.Antenna(antNo).subarrayNumber" val="(corrSubarrayNo)">
								<!-- ignore for a while to avoid transient effects due to tuning -->
								<mp canon="Sldc.Band(bandNoVar).Input(inputNoVar).ifOutPower" alarm_after="300.0" />
							</if>
						</varmap_scope>
						</varmap_scope>
					</range>
				</range>
			</mp>

			<!-- LoReference -->
			<mp canon="LoRef.LoRefDistributionBox1.synthFreqErr" alarm_after="120.0" />
		</transient>
	</attrs_scope>

	<!-- Alarms specific to Subarray 2 (AKA Sci2) -->
	<attrs_scope alarm_prefix="sci2">
		<transient cond="alarmEnableSubarray" subarray="&SCI2;">
			<mp canon="Control.Subarray2.alarm" />
			<mp canon="Control.Subarray2.scriptState" />
			<mp canon="Control.Subarray2.controllerInitialized" />
			<mp canon="WbPipeline.IntegratorStageContainer.IntegratorStage.timeSinceLastIntegration" alarm_after="780.0" />
			<mp canon="WbPipeline.IntegratorStageContainer.IntegratorStage.noData" alarm_after="30.0" />
			<mp canon="WbPipeline.VisBrickStageContainer.VisBrickStage.fileError" alarm_after="30.0" />

			<!-- COBRA Wideband Correlator -->
			<range var="bandNoVar" first="1" last="&WBCBANDS;">

				<!-- valid configuration for all bands -->
				<mp canon="Control.WidebandCorrelator.WbcBand(bandNoVar).ControlBandPoints.configuration" alarm_after="240.0" />

				<!-- check that the band is online first -->
				<mp canon="WbcBand(bandNoVar).online" alarm_after="30.0">

					<!-- for each digitizer -->
					<range var="digNoVar" first="1" last="4">
						<attrs_scope canon_begin="WbcBand(bandNoVar).Digitizer(digNoVar)." alarm_after="30.0">
							<mp canon_last="digATemperature" />
							<mp canon_last="digBTemperature" />
							<mp canon_last="fpga1Temperature" />
							<mp canon_last="fpga3Temperature" />

							<attrs_scope alarm_after="150.0">
								<mp canon_last="DigA.vplus" />
								<mp canon_last="DigA.vzero" />
								<mp canon_last="DigA.vminus" />
								<mp canon_last="DigB.vplus" />
								<mp canon_last="DigB.vzero" />
								<mp canon_last="DigB.vminus" />
							</attrs_scope>
						</attrs_scope>
					</range>

					<!-- for each correlator -->
					<range var="corrNoVar" first="1" last="3">
						<attrs_scope canon_begin="WbcBand(bandNoVar).Correlator(corrNoVar).">
							<mp canon_last="fpga1Temperature" />
							<mp canon_last="fpga7Temperature" />
						</attrs_scope>
					</range>
				</mp>
			</range>

			<!-- COBRA Wideband Downconverter -->

			<!-- check that the dcon machine is producing data -->
			<mp canon="Wbdc.online">

				<!--
					 Check each dcon band + input

					 - the band + input must be connected to any antenna
					 - the correlator band must be in the same subarray as the antenna
				-->
				<range var="bandNoVar" first="1" last="8;">
					<range var="inputNoVar" first="1" last="&WBCINPUTS;">
						<varmap_scope var="antNo" canon="SignalPath.Mapping.WbcBand(bandNoVar).Input(inputNoVar).antennaNo">
						<varmap_scope var="corrSubarrayNo" canon="SignalPath.Mapping.WbcBand(bandNoVar).subarrayNo">
							<if canon="Control.Antenna(antNo).subarrayNumber" val="(corrSubarrayNo)">
								<!-- ignore for a while to avoid transient effects due to tuning -->
									<mp canon="Wbdc.Band(bandNoVar).Input(inputNoVar).ifOutPower" alarm_after="300.0" />
							</if>
						</varmap_scope>
						</varmap_scope>
					</range>
				</range>
				<range var="bandNoVar" first="10" last="&WBCBANDS;">
					<range var="inputNoVar" first="1" last="&WBCINPUTS;">
						<varmap_scope var="antNo" canon="SignalPath.Mapping.WbcBand(bandNoVar).Input(inputNoVar).antennaNo">
						<varmap_scope var="corrSubarrayNo" canon="SignalPath.Mapping.WbcBand(bandNoVar).subarrayNo">
							<if canon="Control.Antenna(antNo).subarrayNumber" val="(corrSubarrayNo)">
								<!-- ignore for a while to avoid transient effects due to tuning -->
									<mp canon="Wbdc.Band(bandNoVar).Input(inputNoVar).ifOutPower" alarm_after="300.0" />
							</if>
						</varmap_scope>
						</varmap_scope>
					</range>
				</range>
								<!-- Silence band9 for this node-->
				<range var="inputNoVar" first="1" last="&WBCINPUTS;">
					<varmap_scope var="antNo" canon="SignalPath.Mapping.WbcBand9.Input(inputNoVar).antennaNo">
					<varmap_scope var="corrSubarrayNo" canon="SignalPath.Mapping.WbcBand9.subarrayNo">
						<if canon="Control.Antenna(antNo).subarrayNumber" val="(corrSubarrayNo)">
							<!-- ignore for a while to avoid transient effects due to tuning -->
								<mp canon="Wbdc.Band9.Input(inputNoVar).ifOutPower" silent="true" />
						</if>
					</varmap_scope>
					</varmap_scope>
				</range>
			</mp>


			<!-- LoReference -->
			<mp canon="LoRef.LoRefDistributionBox2.synthFreqErr" alarm_after="120.0" />
		</transient>
	</attrs_scope>

	<!-- Alarms specific to Subarray 3 (AKA Eng1) -->
	<transient cond="alarmEnableSubarray" subarray="3">
		<mp canon="Control.Subarray3.alarm" />
	</transient>

	<!-- Alarms specific to Subarray 4 (AKA Eng2) -->
	<transient cond="alarmEnableSubarray" subarray="4">
		<mp canon="Control.Subarray4.alarm" />
	</transient>

	<!-- weather station -->
	<mp canon="Weather.online" alarm_after="100.0">
		<mp canon="Weather.averageWindSpeed" alarm_after="100.0" />
	</mp>

	<mp canon="MasterClock.Clock.ntpPpsOffset" />
	<mp canon="MasterClock.Clock.prs10ErrorCode" />
	<mp canon="Dataflow.MonitorDataDeleter.LastRun.peak" />
	<mp canon="Dataflow.AstroheaderWriter.SpectralLineCorrelator.Processing.lagTime" />
	<mp canon="Dataflow.AstroheaderWriter.WidebandCorrelator.Processing.lagTime" />

	<!-- LineLength Subsystem -->
	<mp canon="LineLength.online" alarm_after="60.0">

		<!-- all antennas -->
		<range var="carmaAntNo" first="1" last="23">
			<if canon="Control.Antenna(carmaAntNo).subarrayNumber" val="[12]">
				<mp canon="LineLength.initialized(carmaAntNo)" alarm_after="60.0" />
			</if>
			<mp canon="Control.Antenna(carmaAntNo).ifAttenAmb1" silent="true" alarm_after="60.0" />
		</range>
	</mp>

	<!-- each ovro antenna C2-C6-->
	<range var="ovroAntNo" first="2" last="6">
		<if canon="Control.Antenna(ovroAntNo).subarrayNumber" val="[12]">
			<attrs_scope canon_begin="Ovro(ovroAntNo).">
