=== mpound/carma/conf/fault/blankflag.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--
NOTE: this DTD is meant to be used to verify a pre-processed DAG
NOTE: configuration file only. It does not try to encapsulate any of
NOTE: the shorthands used to construct the original DAG file.
-->

<!-- the top level element -->
<!ELEMENT dag (bf_output|gather|mp)*>
<!ATTLIST dag type (blankflag) #REQUIRED>

<!-- a blanking/flagging output - corresponds to a correlator output -->
<!ELEMENT bf_output (bad|gather_ref|mp|mp_ref|transient|varmap_scope)*>
<!ATTLIST bf_output astroband CDATA #REQUIRED>
<!ATTLIST bf_output astroinput CDATA #REQUIRED>

<!--
     A transient (runtime-changeable) condition

     This allows you to change the DAG at runtime using a control system
     command. You will use it to disable large sections of monitor points
     during certain array configurations.
-->
<!ELEMENT transient (bad|gather_ref|mp|mp_ref|transient|varmap_scope)*>
<!ATTLIST transient cond (correlatorNoiseOff) #REQUIRED>
<!ATTLIST transient subarray CDATA #REQUIRED>

<!-- a grouping of other elements -->
<!ELEMENT gather (bad|gather_ref|mp|mp_ref|transient|varmap_scope)*>
<!ATTLIST gather name CDATA #REQUIRED>

<!-- the gather_ref type does not support masking -->
<!ELEMENT gather_ref EMPTY>
<!ATTLIST gather_ref name CDATA #REQUIRED>

<!--
     Capability to stop evaluation based on monitor point value

     This allows you to "chop off" part of the DAG tree based on the
     value of a monitor point. Everything is done with regular expressions
     to allow for arbitrarily complex matching schemes.

     We also allow negation to make certain regular expressions easier
     to write.
-->
<!ELEMENT if (bad|if|gather_ref|mp|mp_ref|transient|varmap_scope)*>
<!ATTLIST if canon CDATA #REQUIRED>
<!ATTLIST if val CDATA #REQUIRED>
<!ATTLIST if negate (true|false) #IMPLIED>

<!--
     Monitor Point

     This represents an instance of a carma::monitor::MonitorPoint in C++.

     When an <mp> node has children, this effects evaluation. When a "bad"
     node state is encountered, the children are not evaluated, and the first
     bad node in the tree is reported as the error condition.
-->
<!ELEMENT mp (if|mp|mp_ref|transient|varmap_scope)*>
<!ATTLIST mp canon CDATA #REQUIRED>
<!ATTLIST mp bit (DRIVE|MONITORDATA|OFFLINE|PHASELOCK) #REQUIRED>

<!-- the mp_ref type does not support masking -->
<!ELEMENT mp_ref EMPTY>
<!ATTLIST mp_ref canon CDATA #REQUIRED>

<!--
     A Bad Node (always fails evaluation)

     This works exactly like a bad monitor point, but does not add anything
     to the list of faults. It can be used in conjunction with <if> to force
     a certain path through the DAG to cause blanking.
-->
<!ELEMENT bad EMPTY>
<!ATTLIST bad bit (DRIVE|MONITORDATA|OFFLINE|PHASELOCK) #REQUIRED>

<!--
     A way to add a variable expansion based on a monitor point name

     This is useful for allowing runtime changeable monitor point names
     in child nodes without having to enumerate every possibility in
     <if> conditions.

     The information from this variable map is passed into the email
     system. This allows the template engine to have some information
     about the state of the evaluation. For example: antenna number
     connected to a downconverter input.
-->
<!ELEMENT varmap_scope (if|gather_ref|mp|mp_ref|transient|varmap_scope)+>
<!ATTLIST varmap_scope var CDATA #REQUIRED>
<!ATTLIST varmap_scope canon CDATA #REQUIRED>

=== mpound/carma/conf/fault/test/bf_submem.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE dag SYSTEM "blankflag.dtd" [
	<!ENTITY SCI1 "1">
	<!ENTITY SCI2 "2">
	<!ENTITY SLCBANDS "8">
	<!ENTITY WBCBANDS "16">
	<!ENTITY SLCINPUTS "15">
	<!ENTITY WBCINPUTS "8">
]>

<dag type="blankflag">

	<range var="carmaAntNo" first="1" last="23">
		<mp canon="(antSubsys:carmaAntNo).AntennaCommon.Drive.state" bit="DRIVE" />

		<mp canon="(antSubsys:carmaAntNo).AntennaCommon.LO.yigState" bit="PHASELOCK">
			<mp canon="(antSubsys:carmaAntNo).AntennaCommon.LO.loState" bit="PHASELOCK" />
		</mp>
	</range>

	<!-- blanking and flagging outputs (astroband numbered) -->
	<range var="bandNoVar" first="1" last="24">
		<range var="inputNoVar" first="1" last="32">
			<bf_output astroband="(bandNoVar)" astroinput="(inputNoVar)">

				<varmap_scope var="antennaNo" canon="SignalPath.Mapping.Astroband(bandNoVar).Input(inputNoVar).antennaNo">
				<varmap_scope var="corrBandNo" canon="SignalPath.Mapping.Astroband(bandNoVar).Input(inputNoVar).corrBandNo">
				<varmap_scope var="corrBandInputNo" canon="SignalPath.Mapping.Astroband(bandNoVar).Input(inputNoVar).corrBandInputNo">


				<!--
					 This variable is used during the traversal of the per-antenna state
					 to choose which subarray transient state(s) to pick.
				-->
				<varmap_scope var="corrSubarrayNo" canon="SignalPath.Mapping.Astroband(bandNoVar).subarrayNo">

					<!--
						 If this antenna is not being controlled by the same subarray as
						 the correlator band to which it is connected, we must blank it
						 for the pipeline.

						 This handles the special case where the hardware is all physically wired
						 together (antenna receiver, switchyard, dcons, correlator) however the
						 antenna is not being controlled by the same subarray controlling the
						 correlator. In this case, the antenna may be pointed at a completely
						 different place on the sky.
					-->
					<if canon="Control.Antenna(antennaNo).subarrayNumber" val="(corrSubarrayNo)" negate="true">
						<bad bit="OFFLINE" />
					</if>

					<!-- drive system -->
					<mp_ref canon="(antSubsys:antennaNo).AntennaCommon.Drive.state" />

				</varmap_scope>
				</varmap_scope>
				</varmap_scope>
				</varmap_scope>

			</bf_output>
		</range>
	</range>

</dag>
<!-- vim: set ts=4 sts=4 sw=4 noet: -->

=== mpound/carma/conf/fault/blankflag.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE dag SYSTEM "blankflag.dtd" [
	<!ENTITY SCI1 "1">
	<!ENTITY SCI2 "2">
	<!ENTITY SLCBANDS "8">
	<!ENTITY WBCBANDS "16">
	<!ENTITY SLCINPUTS "15">
	<!ENTITY WBCINPUTS "8">
]>

<dag type="blankflag">

	<!-- pre-define antenna specific monitor points: each antenna is one standalone group -->
	<range var="carmaAntNo" first="1" last="23">
		<gather name="antenna(carmaAntNo)_gather">
			<!-- require valid subsystem data -->
			<mp canon="(antSubsys:carmaAntNo).MonitorSubsystemStats.validSubsystem" bit="MONITORDATA">
				<!-- drive system -->
				<mp canon="(antSubsys:carmaAntNo).AntennaCommon.Drive.state" bit="DRIVE" />

				<!-- receiver system -->
				<mp canon="(antSubsys:carmaAntNo).AntennaCommon.LO.yigState" bit="PHASELOCK">
					<mp canon="(antSubsys:carmaAntNo).AntennaCommon.LO.loState" bit="PHASELOCK" />
				</mp>
			</mp>
		</gather>
	</range>

	<!-- blanking and flagging outputs (astroband numbered) -->
	<range var="bandNoVar" first="1" last="24">
		<range var="inputNoVar" first="1" last="32">
			<bf_output astroband="(bandNoVar)" astroinput="(inputNoVar)">

				<varmap_scope var="carmaAntNo" canon="SignalPath.Mapping.Astroband(bandNoVar).Input(inputNoVar).antennaNo">
				<varmap_scope var="corrBandNo" canon="SignalPath.Mapping.Astroband(bandNoVar).Input(inputNoVar).corrBandNo">
				<varmap_scope var="corrBandInputNo" canon="SignalPath.Mapping.Astroband(bandNoVar).Input(inputNoVar).corrBandInputNo">

				<!--
					 This variable is used during the traversal of the per-antenna state
					 to choose which subarray transient state(s) to pick.
				-->
				<varmap_scope var="corrSubarrayNo" canon="SignalPath.Mapping.Astroband(bandNoVar).subarrayNo">

					<!--
						 If this antenna is not being controlled by the same subarray as
						 the correlator band to which it is connected, we must blank it
						 for the pipeline.

						 This handles the special case where the hardware is all physically wired
						 together (antenna receiver, switchyard, dcons, correlator) however the
						 antenna is not being controlled by the same subarray controlling the
						 correlator. In this case, the antenna may be pointed at a completely
						 different place on the sky.
					-->
					<if canon="Control.Antenna(carmaAntNo).subarrayNumber" val="(corrSubarrayNo)" negate="true">
						<bad bit="OFFLINE" />
					</if>

					<!-- per-antenna state -->
					<transient cond="correlatorNoiseOff" subarray="(corrSubarrayNo)">
						<gather_ref name="antenna(carmaAntNo)_gather" />
					</transient>

				</varmap_scope>
				</varmap_scope>
				</varmap_scope>
				</varmap_scope>

			</bf_output>
		</range>
	</range>

</dag>
<!-- vim: set ts=4 sts=4 sw=4 noet: -->
